###### Main Service ######
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeair-authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: acmeair-auth-deployment
  template:
    metadata:
      labels:
        name: acmeair-auth-deployment
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
    spec:
      containers:
      - name: acmeair-authservice-java
        image: emanelsabban/acmeair-microsvc:acmeair-authsvc3
        #image: emanelsabban/acmeair-microsvc:acmeair-authservice-java
        ports:
          - containerPort: 9080
          - containerPort: 9443
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 400Mi
            cpu: 1
          requests:
            memory: 400Mi
            cpu: 400m
        env:
        - name: USERNAME
          value: admin
        - name: PASSWORD
          value: password
        - name: ACMEAIR_STACKAA_CUSTOMER_URL
          value: "http://acmeair-customer-service:9080/customer"
        - name: JAEGER_AGENT_HOST
          value: jaeger-all-in-one-inmemory-agent
        - name: JAEGER_AGENT_PORT
          value: '6832'
        - name: JAEGER_ENDPOINT
          value: 'http://jaeger-all-in-one-inmemory-collector:14268/api/traces'
        - name: ACCESS_LOGGING_ENABLED
          value: 'false'
        - name: TRACE_SPEC
          value: '*=info'
        - name: LOGGING_FORMAT
          value: 'simple'
        - name: JAVA_OPTIONS
          #value: '-XX:+UseJITServer -XX:JITServerAddress=ibm-java-acceleration-server -XX:JITServerTimeout=10000 -Xjit:verbose={compilePerformance|JITServer},vlog=/tmp/vlog.txt'
          value: '-Xjit:verbose={compilePerformance},vlog=/tmp/vlog.txt'        
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 120
          periodSeconds: 15
      nodeSelector:
        chosen: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-auth-service
spec:
  ports:
    - name: 9080-tcp
      protocol: TCP
      port: 9080
      targetPort: 9080
  selector:
    name: acmeair-auth-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-secure-auth-service
spec:
  ports:
    - name: 9443-tcp
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    name: acmeair-auth-deployment